# Generated by Django 4.0.6 on 2022-07-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nombres')),
                ('genero', models.CharField(choices=[('M', 'Mascuilino'), ('F', 'Femenino'), ('N', 'Inseguro')], default='', max_length=1)),
                ('identificacion', models.CharField(max_length=10, verbose_name='Identificacion')),
                ('tipo_identificacion', models.CharField(choices=[('Cedula', 'Cedula'), ('RUC', 'RUC'), ('Pasaporte', 'Passaporte')], default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Persona',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.persona')),
                ('num_cargas_faml', models.PositiveIntegerField(verbose_name='Numero Cargas Familiares')),
                ('fecha_residencia', models.DateField(verbose_name='Fecha residencia')),
                ('estado_civil', models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado'), ('Separado', 'Separado')], default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('id',),
            },
            bases=('api.persona',),
        ),
    ]
